[package]
name = "client"
version = "0.1.0"
authors = ["Phoebe Bell <minaphoebebell@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
slog = "2.5.2"
slog-async = "2.3.0"
slog-term = "2.4.2"