[package]
name = "logformat"
version = "0.1.0"
authors = ["Phoebe Bell <minaphoebebell@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.0"
env_logger = "0.7.1"
log = "0.4.8"